# This override file should be used when running this service in isolation
# to provide required sibling services for local testing

services:
  ? adp-dotnet-test-roz
  : build:
      target: development
    ports:
      - "3007:3007"
    volumes:
      - ./src/Adp.Dotnet.Test.Roz.Api:/home/dotnet/src/Adp.Dotnet.Test.Roz.Api
      - ./src/Adp.Dotnet.Test.Roz.Core:/home/dotnet/src/Adp.Dotnet.Test.Roz.Core